### ISSUE TITLE
いいところ診断の結果に優しさを追加したい。

### ISSUE THREAD

**Issue by okaka230214** [okaka230214/assessment#1]
以下の結果を追加したい。

'{userName}のいいところは優しさです。あなたの優しい雰囲気や立ち振舞に多くの人が癒やされています。'

**Comment by akoh1214** [comment]
これから対応します

**Comment by okaka230214** [comment]
dbdd92b60f2f91b78cd3d6bb7ea5616abd42b7aa　にて対応しました
